import NewPlatformDigitalSubscriptionSubscriptionEController from '../new-platform-digital-subscription-subscription-e';

var NewPlatformDigitalSubscriptionSubscriptionENewController = NewPlatformDigitalSubscriptionSubscriptionEController;
export default NewPlatformDigitalSubscriptionSubscriptionENewController;
