import NewPlatformDigitalSubscriptionApplicationUserEController from '../new-platform-digital-subscription-application-user-e';

var NewPlatformDigitalSubscriptionApplicationUserENewController = NewPlatformDigitalSubscriptionApplicationUserEController;
export default NewPlatformDigitalSubscriptionApplicationUserENewController;
