import NewPlatformDigitalSubscriptionOrganizationEController from '../new-platform-digital-subscription-organization-e';

var NewPlatformDigitalSubscriptionOrganizationENewController = NewPlatformDigitalSubscriptionOrganizationEController;
export default NewPlatformDigitalSubscriptionOrganizationENewController;
