import NewPlatformDigitalSubscriptionVisitEController from '../new-platform-digital-subscription-visit-e';

var NewPlatformDigitalSubscriptionVisitENewController = NewPlatformDigitalSubscriptionVisitEController;
export default NewPlatformDigitalSubscriptionVisitENewController;
